language: java
os:
  - linux
jdk:
  - oraclejdk8
sudo: required
dist: trusty
install: travis_wait 50 mvn install
addons:
  apt:
    packages:
      - oracle-java8-installer
script: 
- "mvn clean install -Dci"